server:
  error:
    include-message: always
    include-binding-errors: always
  http2:
    enabled: true

spring:
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
          fetch_size: 400
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  mail:
    host: smtp.gmail.com
    username: linkking.noreply@gmail.com
    password: wjhkztqvhjzrjlsp
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /api-docs
