server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
          fetch_size: 400
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
  profiles:
    active: dev
