server:
  error:
    include-message: always
    include-binding-errors: always
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/javascript, application/javascript, text/css, application/json, application/xml, text/html, text/xml, text/plain

spring:
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
          fetch_size: 400
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /api-docs
