server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3333/myecommerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet

logging:
  level:
    org.hibernate: ERROR
